In [3]:
import pandas as pd

# Load the CSV file
file_path = r"C:\Users\choud\Downloads\merged_cleaned_text_PaddleOCR2.csv"
df = pd.read_csv(file_path)

# Print column names to identify the text column
print(df.columns)

# Replace 'text' with the actual column name containing your text
text_column = 'text'

# Drop rows where the text is NaN
df = df.dropna(subset=[text_column])

# Define paragraph chunking function
def chunk_by_paragraph(text):
    # Normalize line breaks
    normalized = str(text).replace('\r\n', '\n').replace('\r', '\n')
    # Split on two or more newlines
    paragraphs = [para.strip() for para in normalized.split('\n\n') if para.strip()]
    return paragraphs

# Apply paragraph chunking
df['paragraph_chunks'] = df[text_column].apply(chunk_by_paragraph)

# Explode so each paragraph appears in a new row
df_exploded = df.explode('paragraph_chunks').reset_index(drop=True)

# Save the result to a new CSV
output_path = r"C:\Users\choud\Downloads\paragraph_chunks_output_v2.csv"
df_exploded.to_csv(output_path, index=False)

print(f"Paragraph-chunked file saved to: {output_path}")


Index(['filename', 'text'], dtype='object')
Paragraph-chunked file saved to: C:\Users\choud\Downloads\paragraph_chunks_output_v2.csv


In [1]:
import pandas as pd
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize

# Ensure the punkt tokenizer is available
nltk.download('punkt')


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\choud\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [2]:
# Load your CSV file
file_path = r"C:\Users\choud\Downloads\paragraph_chunks_output.csv"
df = pd.read_csv(file_path)

# Show first few rows to verify
df.head()


,filename,text,paragraph_chunks
0,0_0.txt,[ WIKIPEDIA Donate Create account Log in. The ...,[ WIKIPEDIA Donate Create account Log in. The ...
1,0_1.txt,[ Animation [edit] Year Title Role Notes 1997 ...,[ Animation [edit] Year Title Role Notes 1997 ...
2,0_10.txt,"[ This page was last edited on 20 April 2025, ...","[ This page was last edited on 20 April 2025, ..."
3,0_100.txt,[ Billy Joel's parents met in the late 1930s a...,[ Billy Joel's parents met in the late 1930s a...
4,0_1000.txt,[ Other early instances of women's suffrage in...,[ Other early instances of women's suffrage in...


In [4]:
pip install pandas scikit-learn nltk rouge-score


Note: you may need to restart the kernel to use updated packages.


In [10]:
import nltk
nltk.download('punkt')


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\choud\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [12]:
from nltk.tokenize import TreebankWordTokenizer

tokenizer = TreebankWordTokenizer()
df['tokenized_paragraphs'] = df['paragraphs'].apply(
    lambda paras: [tokenizer.tokenize(p) for p in paras]
)


In [18]:
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))
print(stop_words)


{"haven't", 'theirs', 'those', "mightn't", 'you', 'if', "he'd", 'this', 'hadn', "won't", 'myself', 'just', "isn't", 'we', 'during', 'yours', 'too', 'hers', 'not', 'on', 'about', 'couldn', 'has', 'herself', 'nor', 'of', 'didn', 'isn', 'shan', 'y', 'up', "doesn't", 'an', 'had', 'in', 'our', "we've", 'who', "you're", 'himself', 'whom', "should've", 'where', 'more', 'doesn', "you've", 'these', 'into', 'below', 't', 'ourselves', "she'd", 'her', 'should', 'their', 'which', 'a', 'mustn', 'yourselves', 'o', 'am', 'further', "weren't", 'very', 'the', 'been', "didn't", "they're", 'once', 've', 'as', 'can', 'don', 'won', "hadn't", 'haven', 'above', 'here', "i've", 'them', 'what', 'him', 'against', 'will', 'ma', 'needn', 'down', "we'd", 'ain', 'own', 'having', "she's", 'to', 'until', "couldn't", 'why', 'from', 'd', 'only', 's', 'be', 'have', "we're", 'wouldn', 'when', 'yourself', 'doing', 'both', "it'll", 'because', 'all', 'and', "aren't", 'but', 'any', 'by', 're', 'was', 'such', 'few', 'his', "sh

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\choud\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [20]:
import nltk
nltk.download('punkt')


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\choud\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [21]:
import nltk
nltk


<module 'nltk' from 'C:\\Users\\choud\\anaconda3\\New folder\\Lib\\site-packages\\nltk\\__init__.py'>

In [26]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import nltk
from nltk.translate.bleu_score import sentence_bleu
from rouge_score import rouge_scorer

# Download NLTK data (only once)
try:
    nltk.download('punkt')
except Exception as e:
    print(f"Error downloading NLTK data: {e}")

# Load CSV
csv_path = r"C:\Users\choud\Downloads\paragraph_chunks_output.csv"
df = pd.read_csv(csv_path)

# Assume the text column is named 'text' (change if different)
texts = df['text'].astype(str).tolist()

# Step 1: Compute TF-IDF vectors and cosine similarity matrix
vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = vectorizer.fit_transform(texts)

cosine_sim_matrix = cosine_similarity(tfidf_matrix)

print("Cosine Similarity Matrix:")
print(cosine_sim_matrix)



[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\choud\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


Cosine Similarity Matrix:
[[1.         0.11782578 0.02484442 ... 0.00623005 0.00717927 0.00458821]
 [0.11782578 1.         0.00577332 ... 0.00620644 0.00660912 0.00176914]
 [0.02484442 0.00577332 1.         ... 0.00341372 0.00869556 0.00567732]
 ...
 [0.00623005 0.00620644 0.00341372 ... 1.         0.43742283 0.30637447]
 [0.00717927 0.00660912 0.00869556 ... 0.43742283 1.         0.37998115]
 [0.00458821 0.00176914 0.00567732 ... 0.30637447 0.37998115 1.        ]]


In [34]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import nltk
from nltk.translate.bleu_score import sentence_bleu
from rouge_score import rouge_scorer

# Download NLTK data (only once)
try:
    nltk.download('punkt')
except Exception as e:
    print(f"Error downloading NLTK data: {e}")

# Load CSV
csv_path = r"C:\Users\choud\Downloads\paragraph_chunks_output.csv"
df = pd.read_csv(csv_path)

# Assume the text column is named 'text' (change if different)
texts = df['text'].astype(str).tolist()

# Step 1: Compute TF-IDF vectors and cosine similarity matrix
vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = vectorizer.fit_transform(texts)

cosine_sim_matrix = cosine_similarity(tfidf_matrix)

print("Cosine Similarity Matrix:")
print(cosine_sim_matrix)

# Step 2: Calculate ROUGE and BLEU between pairs (example: first and second text)

# Initialize ROUGE scorer
scorer = rouge_scorer.RougeScorer(['rouge1', 'rougeL'], use_stemmer=True)

# Example: compare first and second chunk
if len(texts) >= 2:
    reference = texts[0]
    candidate = texts[1]

    # ROUGE scores
    rouge_scores = scorer.score(reference, candidate)
    print("\nROUGE scores between first and second text:")
    print(rouge_scores)

    # BLEU score
    reference_tokens = [nltk.word_tokenize(reference.lower())]
    candidate_tokens = nltk.word_tokenize(candidate.lower())
    bleu_score = sentence_bleu(reference_tokens, candidate_tokens)
    print("\nBLEU score between first and second text:")
    print(bleu_score)
else:
    print("Not enough text chunks to compare.")



[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\choud\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


Cosine Similarity Matrix:
[[1.         0.11782578 0.02484442 ... 0.00623005 0.00717927 0.00458821]
 [0.11782578 1.         0.00577332 ... 0.00620644 0.00660912 0.00176914]
 [0.02484442 0.00577332 1.         ... 0.00341372 0.00869556 0.00567732]
 ...
 [0.00623005 0.00620644 0.00341372 ... 1.         0.43742283 0.30637447]
 [0.00717927 0.00660912 0.00869556 ... 0.43742283 1.         0.37998115]
 [0.00458821 0.00176914 0.00567732 ... 0.30637447 0.37998115 1.        ]]

ROUGE scores between first and second text:
{'rouge1': Score(precision=0.29523809523809524, recall=0.18023255813953487, fmeasure=0.22382671480144403), 'rougeL': Score(precision=0.11428571428571428, recall=0.06976744186046512, fmeasure=0.08664259927797834)}


LookupError: 
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - 'C:\\Users\\choud/nltk_data'
    - 'C:\\Users\\choud\\anaconda3\\New folder\\nltk_data'
    - 'C:\\Users\\choud\\anaconda3\\New folder\\share\\nltk_data'
    - 'C:\\Users\\choud\\anaconda3\\New folder\\lib\\nltk_data'
    - 'C:\\Users\\choud\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************
